@REM BURN IN HELL CMAKE FIND PACKAGE AND FKN INVENTOR OF THIS CANCER

SET "PROJ_DIR=%~dp0"
SET "BUILD_DIR=%PROJ_DIR%_build"
SET "PREFIX_DIR=%PROJ_DIR%_prefix"

SET CONFIG=Release
SET NJOBS=8

mkdir "%BUILD_DIR%"
mkdir "%PREFIX_DIR%"

cmake -S "%PROJ_DIR%src" -B "%BUILD_DIR%\AUG" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DBUILD_SHARED_LIBS=OFF
@rem cmake --build "%BUILD_DIR%\AUG" --config %CONFIG% --parallel %NJOBS% --target ALL_BUILD

pause
