@REM BURN IN HELL CMAKE FIND PACKAGE AND FKN INVENTOR OF THIS CANCER

SET "PROJ_DIR=%~dp0"
SET "DEPS_DIR=%PROJ_DIR%deps"
SET "BUILD_DIR=%PROJ_DIR%_build"
SET "PREFIX_DIR=%PROJ_DIR%_prefix"

SET CONFIG=Release
SET "CFLAGS_RELEASE=/MD /DNDEBUG /O2 /Ob2 /Oi /Ot /fp:fast /Gy /GS-"
SET NJOBS=8

mkdir "%BUILD_DIR%"
mkdir "%PREFIX_DIR%"

SET TARGET=fmt
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DFMT_INSTALL=ON ^
	-DFMT_DOC=OFF ^
	-DFMT_TEST=OFF
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=curl
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DBUILD_STATIC_LIBS=ON ^
	-DENABLE_UNICODE=ON ^
	-DBUILD_CURL_EXE=OFF ^
	-DBUILD_LIBCURL_DOCS=OFF ^
	-DBUILD_MISC_DOCS=OFF ^
	-DENABLE_CURL_MANUAL=OFF ^
	-DCURL_USE_LIBPSL=OFF
	
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=SDL
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DSDL_INSTALL=ON ^
	-DSDL_STATIC=ON ^
	-DSDL_SHARED=OFF ^
	-DSDL_TEST=OFF ^
	-DSDL_TEST_LIBRARY=OFF
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=imgui_custom
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=opencv
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DBUILD_WITH_STATIC_CRT=OFF ^
	-DOPENCV_EXTRA_MODULES_PATH="%DEPS_DIR%/opencv_contrib/modules" ^
	-DOPENCV_ENABLE_NONFREE=ON ^
	-DBUILD_opencv_world=ON ^
	-DBUILD_DOCS=OFF ^
	-DBUILD_EXAMPLES=OFF ^
	-DBUILD_TESTS=OFF ^
	-DBUILD_PERF_TESTS=OFF ^
	-DBUILD_JAVA=OFF ^
	-DBUILD_opencv_python2=OFF ^
	-DBUILD_opencv_python3=OFF ^
	-DWITH_OPENMP=OFF ^
	-DWITH_CUDA=OFF ^
	-DWITH_OPENCL=OFF ^
	-DBUILD_JASPER=OFF ^
	-DBUILD_OPENEXR=OFF ^
	-DBUILD_WEBP=OFF ^
	-DWITH_TESSERACT=OFF
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=leptonica
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DSW_BUILD=OFF ^
	-DBUILD_PROG=OFF ^
	-DENABLE_ZLIB=OFF ^
	-DENABLE_PNG=OFF ^
	-DENABLE_GIF=OFF ^
	-DENABLE_JPEG=OFF ^
	-DENABLE_TIFF=OFF ^
	-DENABLE_WEBP=OFF ^
	-DENABLE_OPENJPEG=OFF
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=tesseract
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DSW_BUILD=OFF ^
	-DBUILD_TRAINING_TOOLS=OFF ^
	-DOPENMP_BUILD=OFF ^
	-DFAST_FLOAT=ON ^
	-DGRAPHICS_DISABLED=ON
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=whisper.cpp
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DWHISPER_BUILD_TESTS=OFF ^
	-DWHISPER_BUILD_EXAMPLES=OFF ^
	-DWHISPER_BUILD_SERVER=OFF
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

SET TARGET=libsamplerate
cmake -S "%DEPS_DIR%\%TARGET%" -B "%BUILD_DIR%\%TARGET%" ^
	-DCMAKE_INSTALL_PREFIX="%PREFIX_DIR%" ^
	-DCMAKE_PREFIX_PATH="%PREFIX_DIR%" ^
	-DCMAKE_BUILD_TYPE=%CONFIG% ^
	-DCMAKE_C_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DCMAKE_CXX_FLAGS_RELEASE="%CFLAGS_RELEASE%" ^
	-DBUILD_SHARED_LIBS=OFF ^
	-DLIBSAMPLERATE_INSTALL=ON ^
	-DLIBSAMPLERATE_EXAMPLES=OFF ^
	-DBUILD_TESTING=OFF
cmake --build "%BUILD_DIR%\%TARGET%" --config %CONFIG% --parallel %NJOBS% --target install

pause
